---
kind: pipeline
name: default

steps:
  - name: lint Drone YAML
    image: sdesbure/yamllint:latest
    commands:
      - yamllint .drone.yml

  - name: lint Typescript & Test Server
    image: node:10
    commands:
      - yarn install --prod=false
      - yarn run lint

  - name: deploy to github page
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_user
      password:
        from_secret: github_pawd
    when:
      branch:
        - master
