---
kind: pipeline
name: default

steps:
  - name: lint Drone YAML
    image: sdesbure/yamllint:latest
    commands:
      - yamllint .drone.yml

  - name: lint Typescript
    image: node:10
    commands:
      - yarn install --prod=false
      - yarn run lint

  - name: export static
    image: node:10
    commands:
      - yarn install --prod=false
      - NODE_ENV=production DEPLOY_ENV=github yarn export && touch out/.nojekyll

  - name: deploy to github page
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_user
      password:
        from_secret: github_pawd
      ssh_key:
        from_secret: github_sshkey
      pages_directory: out/
    environment:
      MAIN_HOST:
        from_secret: mainhost
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  - name: deploy to server
    images: appleboy/drone-ssh
    settings:
      host:
        from_secret: server_host
      username:
        from_secret: server_user
      password:
        from_secret: server_pawd
      script:
        - cd digital-certificate-edu/
        - pm2 delete dcert-frontend
        - git fetch origin && git pull origin master
        - pm2 start app-pm2.json
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
